const { createClient } = require('@supabase/supabase-js');
require('dotenv').config({ path: '.env.local' });

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL,
  process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY
);

async function runTest() {
  console.log('--- PHASE 7 E2E TEST ---');
  
  // 1. Authenticate as Admin (who is also coordinator in our test logic usually, or we can just use admin)
  const { data: authData, error: authError } = await supabase.auth.signInWithPassword({
    email: 'testadmin@aimers.example',
    password: 'AIMERS_TestAdmin_2026!'
  });

  if (authError) {
    console.error('Auth failed:', authError);
    return;
  }
  
  console.log('Authenticated as:', authData.user.email);

  // 2. Fetch a token generated by the trigger
  // Admin can read all tokens due to RLS
  const { data: tokens, error: tokenError } = await supabase
    .from('participant_matrix_tokens')
    .select('token, token_type, event_participant_id')
    .limit(1);

  if (tokenError || !tokens.length) {
    console.error('Failed to fetch tokens (or none exist yet):', tokenError || 'No tokens');
    return;
  }

  const testToken = tokens[0];
  console.log('Found generated token:', testToken.token_type);

  // Get the event ID for this token
  const { data: epData } = await supabase
    .from('event_participants')
    .select('event_id')
    .eq('id', testToken.event_participant_id)
    .single();

  const eventId = epData.event_id;

  // 3. Test the scanner RPC (validate_matrix_token)
  // Since we are logged in as admin, the RPC will bypass coordinator check
  console.log(`Testing RPC for Event ${eventId}, Operation: ${testToken.token_type}`);
  
  const { data: rpcSuccess, error: rpcError } = await supabase.rpc('validate_matrix_token', {
    p_event_id: eventId,
    p_operation: testToken.token_type,
    p_token: testToken.token
  });

  console.log('Valid Scan Result:', rpcSuccess);

  // 4. Test Wrong Operation
  const wrongOp = testToken.token_type === 'attendance' ? 'lunch' : 'attendance';
  const { data: rpcWrongOp } = await supabase.rpc('validate_matrix_token', {
    p_event_id: eventId,
    p_operation: wrongOp,
    p_token: testToken.token
  });
  console.log('Wrong Operation Result:', rpcWrongOp);

  // 5. Test Wrong Event
  // Generate random UUID for wrong event
  const wrongEvent = '00000000-0000-0000-0000-000000000000';
  const { data: rpcWrongEvent } = await supabase.rpc('validate_matrix_token', {
    p_event_id: wrongEvent,
    p_operation: testToken.token_type,
    p_token: testToken.token
  });
  console.log('Wrong Event Result:', rpcWrongEvent);

  console.log('--- TEST COMPLETE ---');
}

runTest();
